name: Deploy MultiDocker
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Login Docker
              uses: docker/login-action@v3
              with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build test image
              run: docker build -t react-test -f ./client/Dockerfile.dev ./client

            - name: Run tests
              run: docker run -e CI=true react-test npm test --watch=false

            - name: Build production images
              run: |
                docker build -t scrahen/multi-client ./client
                docker build -t scrahen/multi-nginx ./nginx
                docker build -t scrahen/multi-server ./server
                docker build -t scrahen/multi-worker ./worker

            - name: Push production images
              run: |
                docker push scrahen/multi-client
                docker push scrahen/multi-nginx
                docker push scrahen/multi-server
                docker push scrahen/multi-worker

            - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'

            - name: Deploy to Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v18
              with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                application_name: multi-docker
                environment_name: Multi-docker-env
                existing_bucket_name: elasticbeanstalk-us-east-2-366455674475 
                region: us-east-2
                version_label: ${{ github.sha }}
                deployment_package: deploy.zip